### ISSUE TITLE
As a developer, I want to have collections, so that I can group related documents together.

### ISSUE THREAD

**Issue by rjdahomie** [CS180-spring/cs180-23-quantum#3]
As a developer, I want to have collections, so that I can group related documents together.

**Comment by andykr1k** [comment]
Priority: Low
Story Points: 4
Test Cases: 

When a user wants to create a collection, they will be prompted with an input box with a name field. If the name of the collection is not unique then they will see an error. Once a uniquely named collection is created, it should be shown within the database they created it in. 

Users can change the name of a collection. For instance, a user can update a collection's name within a database and the new name of the collection will reflect this. If the new name has already exists or is not unique, they will be prompted with an error. 
Users can also remove collections. A user can delete a collection by either entering the name of the collection or pressing the delete button via the interface. If a user enters the name of a non-existing collection, they will see an error. If the name exists, the collection will be removed within the database and all existing documents within the collection will also be deleted.

Actionable Tasks:
Connect to db
Create collection in db at specified location
Update a collection in db at specified location
Remove a collection in db at specified location
