### ISSUE TITLE
As a developer, I want to use the export functionality to easily export my data in JSON format, so that I can transfer, back up, or analyze my data elsewhere.

### ISSUE THREAD

**Issue by rjdahomie** [CS180-spring/cs180-23-quantum#9]
As a developer, I want to use the export functionality to easily export my data in JSON format, so that I can transfer, back up, or analyze my data elsewhere.

**Comment by kkadhith** [comment]
Priority: Med
Story Points: 6
Test Cases: To be added

Actionable Tasks:
